const Colors = {
    Aquamarine      :       "#7FFFD4",
    Black           :       "#000",
    Cinza           :       "#363636",
    CinzaDark       :       "#2F4F4F",
    DarkBlue        :       "#00008B",
    DarkCyan        :       "#008B8B",
    DarkGreen       :       "#006400",
    DeepPink        :       "#FF1493",
    DarkRed         :       "#8B0000",
    MidnightBlue    :       "#191970",
    Red             :       "#FF0000",
    RoyalBlue       :	    "#4169E1",
    Thistle         :       "#D8BFD8",
    White           :       "#FFF",
    Yellow          :       "#FFFF00",
};

export const Cor = {
    pri         :   Colors.Black,
    sec         :   Colors.White,
    ter         :   Colors.CinzaDark,
    qua         :   Colors.Black,
    bord        :   Colors.Aquamarine,
    font        :   Colors.White,
    btt         :   Colors.DarkCyan,
    btt_sel     :   Colors.Red,
    btt_font    :   Colors.White,
    tab_sel     :   Colors.DarkBlue,
    tab_bar     :   Colors.Black,
    red         :   Colors.Red,
    white       :   Colors.White,
    black       :   Colors.Black,
    icons_cor   :   Colors.White,
    switOn1     :   Colors.White,
    switOn2     :   Colors.White,
    switOf1     :   Colors.White,
    switOf2     :   Colors.White,
    
};