const icons = {
    rankink     :   "barschart",
    icon_liga   :   "team",
    statis      :   "piechart",
    champ       :   "Trophy",
    king        :   "crown",
    mais_circle :   "pluscircle",
    mais        :   "plus",
    confgs      :   "setting", 
    reload      :   "sync",
    new_jg      :   "dribbble",
    cores       :   "adjust",
    mais        :   "pluscircle",
    pesquisa    :   "magnifying-glass", // Entypo
    user        :   "user",
    team        :   "team",
    add_jgdr    :   "adduser",
    add_liga    :   "addusergroup",
    del_user    :   "deleteuser",
    del_liga    :   "deleteusergroup",
    play_cro    :   "controller-play",
    paused_cro  :   "controller-paus",
    stop        :   "controller-stop",
    incrementa  :   "plus",
    decrementa  :   "minus",
    perfil_user :   "solution1", // 
    setting     :   "setting",
    logout      :   "log-out",

    seta_up     :   "upsquare",
    seta_down   :   "downsquare",
    seta_left   :   "leftsquare",
    seta_right  :   "rightsquare",

}; export default icons;